Repository AY2122S1-CS2103T-T13-4/tp, pull requests merged in 2021-11, with the labels that each got.

#174 Fix Ui Component sizing bug
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FullPersonCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Medium

#176 Fix Dupliacate criteria checking
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, severity.Medium

#187 Update edit command and add more test cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/interests/InterestsList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#191 Fix for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/images/FilterActivityDiagram.png
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/comparators/PersonComparator.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: v1.4

#195 Fix DG for v1.4
  docs/DeveloperGuide.md
Labels: v1.4

#193 Fix 1.4
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DuplicateImportDecision.puml
  docs/diagrams/ImportDecision.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageClassDiagram2.puml
  docs/images/DuplicateImportDecision.png
  docs/images/ImportDecision.png
  docs/images/StorageClassDiagram.png
  docs/team/idgrr.md
Labels: v1.4

#194 Update UG, DG, EditCommand and EditCommandTest
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditActivityDiagram.puml
  docs/images/EditActivityDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/interests/InterestsList.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: v1.4

#216 Add PPP
  docs/team/pranav-ganesh.md
Labels: priority.High
