Repository AY2122S1-CS2103T-T13-4/tp, pull requests merged in 2021-10, with the labels that each got.

#66 Fix DG and HelpWindow formatting
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: v1.2

#67 Fix IsDone Attribute value type
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/IsDone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/IsDoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.High

#73 Update UG
  docs/UserGuide.md
Labels: type.Enhancement, type.Chore

#74 Update Interest
  src/main/java/seedu/address/model/person/interests/InterestsList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/FullPersonCard.java
Labels: v1.3
